### ISSUE TITLE
IndieGala update: now requires Captcha

### ISSUE THREAD

**Issue by blue-lightning** [Hafas/indiegala-auto-enter#10]
As of 2017-06-21, each time a person enters a giveaway a Captcha is presented to be completed. Tough one to crack here, Hafas.

**Comment by Hafas** [comment]
Thanks for informing me.

I updated the Readme.

**Comment by blue-lightning** [comment]
Should wait at least 2 weeks to make sure the decision is final and all, but if they do, how about forking a new script? Its only function would be to highlight valid GAs on each page so that we could enter them faster.
Also, IndieGala just introduced a bidding system. Great.

**Comment by Hafas** [comment]
Captchas seem to be gone for now.

**Comment by blue-lightning** [comment]
Want to let you know that IndieGala updated its layout again.
