### ISSUE TITLE
Blacklist not working for a specific giveaway

### ISSUE THREAD

**Issue by blue-lightning** [Hafas/indiegala-auto-enter#11]
For the past week a user have periodically giving away the game "Sleengster 3" and my script auto joined everytime. The problem is that I already had "Sleengster 3" and /Sleengster/i in the game blacklist, also that username "( : Don'tFlush : )" in the user blacklist but it's not working.
Here's the [latest](https://www.indiegala.com/giveaways/detail/310707) one.

**Comment by Hafas** [comment]
Can't reproduce. I've added the game in my blacklist and logs says (when `debug` is enabled):

    Not entering 'Sleengster 3' because this game is on my blacklist

Removed the game and put the user instead in my blacklist:

    Not entering 'Sleengster 3' because the user '( : Don'tFlush : )' is on my blacklist

Seems to work as intended.
Can you please post your full `options`-Object?

**Comment by blue-lightning** [comment]
Sorry, just me being stupid. I hadn't realized that it was the same old giveaway. I kept seeing it in the "GA in progress" section and hadn't noticed that it was from 2 months ago.
