### ISSUE TITLE
Add option to blacklist based on IDs instead of names

### ISSUE THREAD

**Issue by blue-lightning** [Hafas/indiegala-auto-enter#14]
The site's checking for owned games feature has been removed, so joinOwnedGames is broken. Checking through Steam's API is a big change and would probably take much of your time, so I think it's easier to just filter by IDs and let users like me copy the owned list ourselves from [here](https://store.steampowered.com/dynamicstore/userdata/).

**Comment by Hafas** [comment]
I'm looking into the Steam API solution.
If I understand the API correctly then I only need to check if `rgOwnedPackages` contains the game's id?

**Comment by Hafas** [comment]
I decided to use [this API](https://developer.valvesoftware.com/wiki/Steam_Web_API#GetOwnedGames_.28v0001.29) instead, because this one doesn't need you to be logged into the Steam Store.

**Comment by blue-lightning** [comment]
shouldEnter() still use joinOwnedGames.

**Comment by Hafas** [comment]
My bad. Should be fixed now.

**Comment by blue-lightning** [comment]
Oh, one more thing: in the readme file, I think it would be better if you have a note about where to get the Steam API key and Steam ID (64, not 32 or 3. I made that mistake). Not sure where you got yours, but I use https://profile.tf for SteamID and https://steamcommunity.com/dev/apikey for API key.
