### ISSUE TITLE
Error in ViolentMonkey and Tampermonkey

### ISSUE THREAD

**Issue by blue-lightning** [Hafas/indiegala-auto-enter#15]
ViolentMonkey (my primary userscript addon): script doesn't run when activating skipOwnedGames. Error: "ReferenceError: "GM is not defined"" from getFromCache().
Tampermonkey (since readme recommend it): popup a warning about cross-origin resource, and a note: "Please note that userscript authors can avoid this dialog by adding @connect tags ⬀ to their scripts."

**Comment by Hafas** [comment]
Does adding
`// @require https://greasemonkey.github.io/gm4-polyfill/gm4-polyfill.js`

solve your ViolentMonkey problem?

**Comment by Hafas** [comment]
Try this:
```
// ==UserScript==
// @name         IndieGala: Auto-enter Giveaways
// @version      2.1.2
// @description  Automatically enters IndieGala Giveaways
// @author       Hafas (https://github.com/Hafas/)
// @match        https://www.indiegala.com/giveaways*
// @grant        GM.xmlHttpRequest
// @grant        GM.getValue
// @grant        GM.setValue
// @grant        GM.deleteValue
// @grant        GM_xmlhttpRequest
// @grant        GM_getValue
// @grant        GM_setValue
// @grant        GM_deleteValue
// @require      https://greasemonkey.github.io/gm4-polyfill/gm4-polyfill.js
// @connect      api.steampowered.com
// ==/UserScript==
```

**Comment by blue-lightning** [comment]
It works now, thanks.

Strange though that script is now stuck at page 1 for a while now
`navigating to /giveaways/2/expiry/asc/level/all
Navigation seems stuck. Retrying ...`
But it's working before with the same code, so probably something on my end. Will report back tomorrow.
