### ISSUE TITLE
Keep user settings between versions

### ISSUE THREAD

**Issue by blue-lightning** [Hafas/indiegala-auto-enter#17]
Since userscript managers auto-update scripts by default, user settings will be lost between versions. Store in local is enough in most cases since people often don't use the same account for both work and home, I think, but apparently uBlockOrigin [manages to store settings in cloud too](https://github.com/gorhill/uBlock/wiki/Cloud-storage).

**Comment by Hafas** [comment]
I doubt a userscript has access to a browser's sync feature.
To prevent losing settings between versions we'd have to store and retrieve them with `GM.setValue` and `GM.getValue`, I suppose. The "problem" is: How do we make the settings editable if we remove them from the script.

How about we inject a `textfield` in the giveaway page?
