### ISSUE TITLE
Handle "extra odds"

### ISSUE THREAD

**Issue by Lucki** [Hafas/indiegala-auto-enter#21]
Would be nice to skip entirely or maybe enter a specified amount of tickets for the "extra odds" giveaways.

**Comment by Hafas** [comment]
You can now set the option `extraTickets` to `0` to not enter the extra odds giveaways.

**Comment by Lucki** [comment]
Thanks!

**Comment by Lucki** [comment]
After some observation I think there's something wrong going on…

I've set the value to `1` so only one extra odd ticket should be bought. But I've seen the script entering a giveaway I've already entered twice. So now I own three tickets in total.

The console tells me the script thinks I haven't entered before: `boughtTickets: 0`
~~~
Entering giveaway Object { id: "528633", name: "The Deed", price: 1, minLevel: 0, owned: false, participants: 1683, guaranteed: true, by: "Anus Treasure", boughtTickets: 0, extraOdds: true, … }
giveaway entered payload Object { status: "ok", …
~~~

But when clicking on the same object in the console it changes to `"boughtTickets": 1`
~~~
{
  "id": "528633",
  "name": "The Deed",
  "price": 1,
  "minLevel": 0,
  "owned": false,
  "participants": 1683,
  "guaranteed": true,
  "by": "Anus Treasure",
  "boughtTickets": 1,
  "extraOdds": true,
  "steamId": "420740",
  "gameId": "420740",
  "gameType": "game"
}
~~~

**Comment by Hafas** [comment]
Confirmed. There seems to be an error when reading the entered tickets. I'll look into it on Saturday (probably).

**Comment by Hafas** [comment]
Should work now.

**Comment by Lucki** [comment]
Yes, it's working now, thank you!
