### ISSUE TITLE
Can't fetch coins data

### ISSUE THREAD

**Issue by IvanpAEG** [Hafas/indiegala-auto-enter#23]
I'm getting this error in console

"GET https://www.indiegala.com/get_user_info?show_coins=True 404"

![imagen](https://user-images.githubusercontent.com/34457043/80615481-05ea4280-8a40-11ea-917c-97e036b3bc30.png)

![imagen](https://user-images.githubusercontent.com/34457043/80615524-13073180-8a40-11ea-968c-8dbd14f84918.png)

**Comment by Hafas** [comment]
Should be fixed now.
The request will still be made in case the API returns but the script will continue as usual if the request fails.
