### ISSUE TITLE
New IndieGala interface

### ISSUE THREAD

**Issue by IvanpAEG** [Hafas/indiegala-auto-enter#24]
Indiegala giveaways have new interface
![imagen](https://user-images.githubusercontent.com/34457043/84564822-fbbca300-ad64-11ea-90a7-6f0275b49cd7.png)

Looks like script is not working with new interface
![imagen](https://user-images.githubusercontent.com/34457043/84564821-f2cbd180-ad64-11ea-9880-141d76cb3193.png)

**Comment by Hafas** [comment]
Sorry - I'm currently short of time. I'll see if I can fix it next weekend.

**Comment by Qayden** [comment]
Any update on this?

**Comment by Hafas** [comment]
I haven't forgotten it but my time is currently limited.

**Comment by Qayden** [comment]
Alright, thanks for letting us know.

**Comment by Hafas** [comment]
I've released an update with a fix.

Some changes to notice:
- You won't see the script navigating to the next page anymore. Indiegala is doing that with ajax requests now and so does the script (without updating the UI part)
- Indiegala does not give the user an indicator if he/she has entered an extra odd giveaway, so I haven't given it a thought yet how to handle it.
- Indiegala does not show anymore who created the giveaway. So blacklisting by user won't work.
