### ISSUE TITLE
[Feature Request] Only enter high-leveled giveaways

### ISSUE THREAD

**Issue by metapone** [Hafas/indiegala-auto-enter#26]
If my level is 2 for example, only enter giveaways with a minimum level of 2 would increase my chance a lot more than entering level 0 and 1 ones. Would this be possible?

**Comment by Hafas** [comment]
Shouldn't be a problem. Do you have a proposal how the option could look like?

My suggestion would be to add a new option `minLevel`, which would default to `0`.
If you set a positive number then it would behave as you expect (from `minLevel` to `currentLevel`)
If you set a negative number then it would go from `currentLevel - abs(minLevel) + 1` to `currentLevel`.

So let's say you are level 3 and enter `-1` then you will only enter level 3 giveaways.
If you enter `-2` and you will additionally also enter level 2 giveaways.
If your level increases to 4 and keep it at `-2`, you will only enter level 3-4 giveaways.

Does this sound good or am I over-complicating things :smile: ?

**Comment by metapone** [comment]
I don't think many users like negative numbers 😄. So just positive `minLevel` is enough. In you want more, throw in a `maxLevel` defaulted to `currentLevel`. To be honest I don't like using negatives  because then I won't know at a glance if they are subtracted from the start or the end position of the range.

**Comment by Hafas** [comment]
Done
