### ISSUE TITLE
[Suggestion] Check won giveaways

### ISSUE THREAD

**Issue by Evanito** [Hafas/indiegala-auto-enter#3]
Some functionality to automatically check all the completed giveaways would save some time.

**Comment by Hafas** [comment]
It's on my to-do list, but it's not a priority right now. Sorry.

**Comment by zypA13510** [comment]
Hi everyone,
I did some research on this today, the API seems not too hard to understand.

Request URL:https://www.indiegala.com/giveaways/check_if_won
Request Method:POST
Form Data:{"entry_id":<$.find("#entry_id")>}

Haven't tested it yet.

**Comment by Hafas** [comment]
The API isn't hard indeed, but If want to write a user friendly script it should do more than just sending some ajax-requests.

I'm currently copy-pasting manually the following code in the browser's console and then refresh the page. 
```
$(".winner-ticket-cont input").each(function (i, input) {
  $.ajax({
    type: "POST",
    url: "/giveaways/check_if_won",
    data: JSON.stringify({
      entry_id: input.value
    }),
    dataType: "json"
  });
}); 
```

It's good enough for me, but as I said: Not user friendly and since IndieGala only displays 20 giveaways at a time, you have to do it a couple of times.

**Comment by zypA13510** [comment]
I have an idea, don't know if it will work though:
If we make use of ajax and request the same page (\profile) a second time, it should return another HTML containing 20 giveaways right? Then we find all the inputs in the payload and repeat the same thing until there is no more input in the resulting payload, then we refresh the page. All giveaways won should now be in the "won" section.

**Comment by Hafas** [comment]
> If we make use of ajax and request the same page (\profile) a second time, 

The correct URL to get the next 20 giveaways is https://www.indiegala.com/giveaways/library_completed , but yeah - this is basically how it can be done. Instead of refreshing the page I would replace the DOM, so the user doesn't have to navigate manually to the completed tab.

**Comment by Hafas** [comment]
Check this out: https://github.com/Hafas/indiegala-check-won
