### ISSUE TITLE
Script cannot get coins value

### ISSUE THREAD

**Issue by zypA13510** [Hafas/indiegala-auto-enter#5]
The API used by this script https://www.indiegala.com/giveaways/get_user_level_and_coins no longer returns coins and recharge time. As a result, my.coins and my.nextRecharge is NaN. The script keeps refreshing the page but actually did nothing.

**Comment by zypA13510** [comment]
I have submitted a patch here:
#4

**Comment by Hafas** [comment]
Thank you very much for your contribution. Merged & added some adjustments.
