### ISSUE TITLE
Script isn't working

### ISSUE THREAD

**Issue by Roboron3042** [Hafas/indiegala-auto-enter#7]
It seems that the script isn't working as of 11/3/2017. Maybe Indiegala has changed their structure/api?

**Comment by Hafas** [comment]
Confirmed.
I'll release a temporary fix in a few minutes.

**Comment by Hafas** [comment]
This commit fixes the issue: https://github.com/Hafas/indiegala-auto-enter/commit/ef6ac18029ed47080f7ee7ac9ee38ef43483421b
Thanks for your report.
