### ISSUE TITLE
Disable entering DLC giveaways

### ISSUE THREAD

**Issue by blue-lightning** [Hafas/indiegala-auto-enter#8]
If you can, an option like that would be nice for a lot of users.
For example, here's a giveaway for a DLC wasting 192 coins:
https://www.indiegala.com/giveaways/detail/256707

**Comment by Hafas** [comment]
IndieGala does not (as far as I can tell) provide the information whether a giveaway is a DLC or not. I would need to make an additional request to the Steam Store to get that information.

I'll add this and an option for `maxPrice` to my to-do-list.

**Comment by blue-lightning** [comment]
I think checking whether an ID is a DLC everytime is indeed too much. MaxPrice is far more reasonable and easier to implement.

**Comment by Hafas** [comment]
I added two new options: `maxPrice` and `skipDLCs`. Both options do what you expect.

`skipDLCs` has an extra option `"missing_basegame"` which will only skip DLCs of which you don't own the basegame.
